proxy:
  secretToken: "[insert here]"
  https:
    hosts:
      - juphub.likeanimalmuch.space
    letsencrypt:
      contactEmail: mll469@nyu.edu
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
singleuser:
  image:
    # Get the latest image tag at:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    name: jupyter/datascience-notebook
    tag: latest
auth:
  type: google
  google:
    clientId: "[insert here].apps.googleusercontent.com"
    clientSecret: "[insert here]"
    callbackUrl: "https://juphub.likeanimalmuch.space/hub/oauth_callback"
    hostedDomain: "nyu.edu"
    loginService: "New York University"
